version: '3'
services:
  mysql-master:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-master-data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always

volumes:
  mysql-master-data:
